import type { Accessory, AccessoryCategory } from '@/lib/types';

export const INITIAL_ACCESSORY_CATEGORIES: AccessoryCategory[] = [
  { id: 'cat-cases', name: 'Mobile Cases', slug: 'mobile-cases', icon: '📱', sort_order: 1 },
  { id: 'cat-screen', name: 'Screen Protectors', slug: 'screen-protectors', icon: '🛡️', sort_order: 2 },
  { id: 'cat-chargers', name: 'Chargers', slug: 'chargers', icon: '🔌', sort_order: 3 },
  { id: 'cat-cables', name: 'Charging Cables', slug: 'charging-cables', icon: '⚡', sort_order: 4 },
  { id: 'cat-powerbanks', name: 'Power Banks', slug: 'power-banks', icon: '🔋', sort_order: 5 },
  { id: 'cat-earphones', name: 'Earphones', slug: 'earphones', icon: '🎧', sort_order: 6 },
  { id: 'cat-tws', name: 'TWS / Wireless Earbuds', slug: 'tws-earbuds', icon: '🎵', sort_order: 7 },
  { id: 'cat-neckbands', name: 'Neckbands', slug: 'neckbands', icon: '🎛️', sort_order: 8 },
  { id: 'cat-speakers', name: 'Bluetooth Speakers', slug: 'bluetooth-speakers', icon: '🔊', sort_order: 9 },
  { id: 'cat-watches', name: 'Smart Watches', slug: 'smart-watches', icon: '⌚', sort_order: 10 },
  { id: 'cat-holders', name: 'Phone Holders', slug: 'phone-holders', icon: '🧲', sort_order: 11 },
  { id: 'cat-car', name: 'Car Accessories', slug: 'car-accessories', icon: '🚗', sort_order: 12 },
  { id: 'cat-adapters', name: 'Adapters', slug: 'adapters', icon: '🔌', sort_order: 13 },
  { id: 'cat-memory', name: 'Memory Cards', slug: 'memory-cards', icon: '💾', sort_order: 14 },
  { id: 'cat-otg', name: 'OTG Adapters', slug: 'otg-adapters', icon: '🔄', sort_order: 15 },
  { id: 'cat-camera', name: 'Camera Accessories', slug: 'camera-accessories', icon: '📷', sort_order: 16 },
  { id: 'cat-cleaning', name: 'Cleaning Accessories', slug: 'cleaning-accessories', icon: '✨', sort_order: 17 },
  { id: 'cat-other', name: 'Other Accessories', slug: 'other-accessories', icon: '📦', sort_order: 18 },
];

export const INITIAL_ACCESSORIES: Accessory[] = [
  {
    id: 'acc-apple-20w-adapter',
    name: 'Apple 20W USB-C Power Adapter',
    brand: 'Apple',
    category: 'Chargers',
    subcategory: 'Power Adapters',
    model_sku: 'MHJE3HN/A',
    price: 1699,
    original_price: 1900,
    discount_price: 1699,
    discount_percent: 11,
    offer: 'Special In-Store Offer',
    stock: 25,
    color: 'White',
    compatibility: 'iPhone 16, 15, 14, 13, 12, 11 series, iPad Pro, iPad Air',
    description: 'The Apple 20W USB-C Power Adapter offers fast, efficient charging at home, in the office, or on the go. While the power adapter is compatible with any USB-C-enabled device, Apple recommends pairing it with iPad Pro and iPad Air for optimal charging performance.',
    specs: { wattage: '20W', port_type: 'USB-C', fast_charging: 'PD 3.0', warranty: '1 Year Official Apple Warranty' },
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800'],
    image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800',
    is_featured: true,
    is_active: true,
    published: true,
    available: true,
    tags: ['apple', 'charger', 'adapter', 'type-c', 'fast-charging'],
    average_rating: 4.9,
    review_count: 38,
    sold_count: 142,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'acc-samsung-25w-typec',
    name: 'Samsung 25W Type-C Super Fast Charger',
    brand: 'Samsung',
    category: 'Chargers',
    subcategory: 'Power Adapters',
    model_sku: 'EP-TA800NBEGIN',
    price: 1299,
    original_price: 1699,
    discount_price: 1299,
    discount_percent: 24,
    offer: 'Save ₹400 Today',
    stock: 30,
    color: 'Black',
    compatibility: 'Samsung Galaxy S24, S23, S22, A55, A35, M55, Z Fold & Flip series',
    description: 'Give your devices the powerful charging support they deserve. Wall Charger for Super Fast Charging (25W) provides Super Fast Charging at up to 25W for capable devices.',
    specs: { wattage: '25W', port_type: 'Type-C', technology: 'Super Fast Charging USB PD 3.0 PPS', warranty: '6 Months Samsung Warranty' },
    images: ['https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=800'],
    image_url: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=800',
    is_featured: true,
    is_active: true,
    published: true,
    available: true,
    tags: ['samsung', 'charger', 'type-c', 'fast-charging'],
    average_rating: 4.8,
    review_count: 27,
    sold_count: 98,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'acc-boat-airdopes-141',
    name: 'boAt Airdopes 141 ANC TWS Earbuds',
    brand: 'boAt',
    category: 'TWS / Wireless Earbuds',
    subcategory: 'Wireless Earbuds',
    model_sku: 'AIRDOPES-141-ANC',
    price: 1499,
    original_price: 4490,
    discount_price: 1499,
    discount_percent: 67,
    offer: 'Flat 67% Off',
    stock: 20,
    color: 'Gunmetal Black',
    compatibility: 'All Android & iOS smartphones, tablets, laptops with Bluetooth',
    description: 'Experience crystal clear audio with active noise cancellation up to 32dB, ENx quad-mic tech for clear calls, and up to 42 hours of playback.',
    specs: { playback: 'Up to 42 Hours', anc: 'Up to 32dB', bluetooth: 'v5.3', latency: '50ms Beast Mode', water_resistance: 'IPX5' },
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800'],
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
    is_featured: true,
    is_active: true,
    published: true,
    available: true,
    tags: ['boat', 'earbuds', 'tws', 'wireless', 'anc'],
    average_rating: 4.7,
    review_count: 54,
    sold_count: 210,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'acc-anker-powercore-10k',
    name: 'Anker PowerCore 10000mAh Power Bank 22.5W Fast Charge',
    brand: 'Anker',
    category: 'Power Banks',
    subcategory: 'Fast Charge Power Banks',
    model_sku: 'A1256',
    price: 1999,
    original_price: 2999,
    discount_price: 1999,
    discount_percent: 33,
    offer: 'Free USB-C Cable Included',
    stock: 15,
    color: 'Matte Black',
    compatibility: 'Universal compatibility: iPhone, Samsung, OnePlus, Xiaomi, Pixel',
    description: 'Ultra-compact high-speed portable charger with PowerIQ and VoltageBoost technology. Built with multi-protection safety system to keep your devices protected.',
    specs: { capacity: '10000mAh', output: '22.5W Max', ports: '1x USB-C + 2x USB-A', weight: '212g', warranty: '18 Months Anker Warranty' },
    images: ['https://images.unsplash.com/photo-1609592426508-cc0279740156?w=800'],
    image_url: 'https://images.unsplash.com/photo-1609592426508-cc0279740156?w=800',
    is_featured: true,
    is_active: true,
    published: true,
    available: true,
    tags: ['anker', 'powerbank', 'battery', 'portable', 'fast-charge'],
    average_rating: 4.9,
    review_count: 19,
    sold_count: 65,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'acc-spigen-tough-armor-ip15',
    name: 'Spigen Tough Armor MagFit Case for iPhone 15 Pro',
    brand: 'Spigen',
    category: 'Mobile Cases',
    subcategory: 'Rugged MagSafe Cases',
    model_sku: 'ACS06718',
    price: 1799,
    original_price: 2499,
    discount_price: 1799,
    discount_percent: 28,
    offer: 'MagSafe Compatible',
    stock: 18,
    color: 'Gunmetal',
    compatibility: 'Apple iPhone 15 Pro (6.1 inch)',
    description: 'Combination of TPU and Polycarbonate for dual protection from drops and scratches. Reinforced kickstand with raised lips to protect screen and camera.',
    specs: { material: 'TPU + Polycarbonate', drop_protection: 'Air Cushion Tech Mil-grade', magsafe: 'Yes', built_in_kickstand: 'Yes' },
    images: ['https://images.unsplash.com/photo-1601593346740-925612772716?w=800'],
    image_url: 'https://images.unsplash.com/photo-1601593346740-925612772716?w=800',
    is_featured: true,
    is_active: true,
    published: true,
    available: true,
    tags: ['spigen', 'case', 'cover', 'iphone', 'magsafe'],
    average_rating: 4.8,
    review_count: 31,
    sold_count: 88,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'acc-noise-colorfit-pro5',
    name: 'Noise ColorFit Pro 5 Max AMOLED Smart Watch',
    brand: 'Noise',
    category: 'Smart Watches',
    subcategory: 'Bluetooth Calling Watches',
    model_sku: 'WRNB-COLORFIT-PRO5',
    price: 2999,
    original_price: 7999,
    discount_price: 2999,
    discount_percent: 62,
    offer: 'Hot Deal · Best Seller',
    stock: 12,
    color: 'Elite Black',
    compatibility: 'Android 9.0+ / iOS 11.0+',
    description: '1.96-inch AMOLED display with always-on feature, Tru Sync Bluetooth calling, functional crown, 100+ sports modes, and 7-day battery life.',
    specs: { display: '1.96 AMOLED (410x502)', battery: 'Up to 7 Days', calling: 'BT Calling with Mic & Speaker', sensors: 'Heart Rate, SpO2, Sleep' },
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800'],
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    is_featured: true,
    is_active: true,
    published: true,
    available: true,
    tags: ['noise', 'smartwatch', 'amoled', 'calling'],
    average_rating: 4.7,
    review_count: 42,
    sold_count: 115,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'acc-tempered-glass-9h',
    name: 'Edge-to-Edge 9H Privacy Tempered Glass Screen Protector',
    brand: 'Arona Guard',
    category: 'Screen Protectors',
    subcategory: 'Privacy Tempered Glass',
    model_sku: 'AG-PRIV-9H',
    price: 499,
    original_price: 999,
    discount_price: 499,
    discount_percent: 50,
    offer: 'Free Installation at Store',
    stock: 50,
    color: 'Black Border (Privacy)',
    compatibility: 'Available for all iPhone, Samsung S/A series, OnePlus models',
    description: 'Anti-peeping 28-degree privacy filter prevents side viewing. 9H surface hardness protects your smartphone screen from shattering and scratches.',
    specs: { hardness: '9H Tempered Glass', privacy_angle: '28 Degrees', coating: 'Oleophobic Hydrophobic', thickness: '0.33mm' },
    images: ['https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800'],
    image_url: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800',
    is_featured: false,
    is_active: true,
    published: true,
    available: true,
    tags: ['tempered-glass', 'screen-protector', 'privacy', 'glass'],
    average_rating: 4.9,
    review_count: 65,
    sold_count: 320,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'acc-braided-typec-cable-65w',
    name: 'Heavy Duty 1.5M Braided Type-C to Type-C 65W Fast Cable',
    brand: 'Stuffcool',
    category: 'Charging Cables',
    subcategory: 'Type-C Cables',
    model_sku: 'SC-C2C-65W',
    price: 499,
    original_price: 999,
    discount_price: 499,
    discount_percent: 50,
    offer: 'Buy 2 Get Extra 10% Off in store',
    stock: 40,
    color: 'Metallic Grey',
    compatibility: 'Laptops, MacBooks, iPads, Galaxy S24, iPhone 15/16, OnePlus',
    description: 'Ultra-durable nylon braided exterior with 25,000+ bend lifespan. Supports 65W Power Delivery fast charging and 480Mbps high-speed data transfer.',
    specs: { length: '1.5 Meters', power: '65W Fast Charging PD', data_rate: '480 Mbps', material: 'Military Grade Braided Nylon' },
    images: ['https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=800'],
    image_url: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=800',
    is_featured: false,
    is_active: true,
    published: true,
    available: true,
    tags: ['cable', 'type-c', '65w', 'fast-charging', 'braided'],
    average_rating: 4.8,
    review_count: 22,
    sold_count: 180,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  }
];

export function normalizeAccessory(a: any): Accessory {
  const primaryImg = a.image_url || (Array.isArray(a.images) && a.images[0]) || '';
  const imgList = Array.isArray(a.images) && a.images.length > 0 
    ? a.images 
    : (primaryImg ? [primaryImg] : []);
  
  const price = Number(a.price) || 0;
  const originalPrice = a.original_price !== undefined && a.original_price !== null ? Number(a.original_price) : undefined;
  const discountPrice = a.discount_price !== undefined && a.discount_price !== null ? Number(a.discount_price) : undefined;
  const discountPercent = a.discount_percent !== undefined && a.discount_percent !== null 
    ? Number(a.discount_percent) 
    : (originalPrice && originalPrice > price ? Math.round(((originalPrice - price) / originalPrice) * 100) : 0);
  
  const stock = Number(a.stock) || 0;
  const isActive = a.is_active ?? a.published ?? true;
  const isFeatured = Boolean(a.is_featured ?? a.featured);
  const available = a.available ?? (stock > 0 && isActive);

  return {
    ...a,
    id: String(a.id),
    name: a.name || 'Mobile Accessory',
    brand: a.brand || 'Other',
    category: a.category || 'Other Accessories',
    subcategory: a.subcategory || '',
    model_sku: a.model_sku || '',
    price,
    original_price: originalPrice,
    discount_price: discountPrice,
    discount_percent: discountPercent,
    offer: a.offer || '',
    stock,
    color: a.color || '',
    compatibility: a.compatibility || '',
    description: a.description || '',
    specs: typeof a.specs === 'object' && a.specs !== null ? a.specs : {},
    images: imgList,
    image_url: primaryImg,
    is_featured: isFeatured,
    is_active: isActive,
    published: isActive,
    available,
    tags: Array.isArray(a.tags) ? a.tags : ['accessory', (a.brand || '').toLowerCase(), (a.category || '').toLowerCase()],
    average_rating: Number(a.average_rating) || 4.8,
    review_count: Number(a.review_count) || 0,
    sold_count: Number(a.sold_count) || 0,
    created_at: a.created_at || '2026-01-01T00:00:00.000Z',
    updated_at: a.updated_at || '2026-01-01T00:00:00.000Z',
  };
}
